# Generated by Django 5.2.12 on 2026-03-09 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[("Hot", "Hot"), ("Cold", "Cold")], max_length=4
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "prices",
                    models.CharField(
                        help_text="Example: 3.50,4.50,5.50",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Type three numbers separated by commas without spaces",
                                regex="^d+(.d{1,2})?,d+(.d{1,2})?,d+(.d{1,2})?$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sugar_free", models.BooleanField(default=False)),
            ],
        ),
    ]
