# Generated by Django 5.2.12 on 2026-03-10 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Arabica", "Arabica"),
                            ("Robusta", "Robusta"),
                            ("Single-Origin Coffee", "Single-Origin Coffee"),
                        ]
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default_bean.jpg", upload_to="beans/"),
                ),
                ("country", models.CharField(max_length=30)),
                ("roast", models.PositiveIntegerField()),
                ("flavor_notes", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="drink",
            name="image",
            field=models.ImageField(default="default_drink.jpg", upload_to="drinks/"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="prices",
            field=models.CharField(
                help_text="Example: 3.50,4.50,5.50",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Type three numbers separated by commas without spaces",
                        regex="^\\d+(\\.\\d{1,2})?,\\d+(\\.\\d{1,2})?,\\d+(\\.\\d{1,2})?$",
                    )
                ],
            ),
        ),
    ]
