# Generated by Django 5.2.12 on 2026-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_bean_drink_image_alter_drink_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
