# Generated by Django 5.2.12 on 2026-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_bean_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="roast",
            field=models.CharField(
                choices=[("Light", "Light"), ("Medium", "Medium"), ("Dark", "Dark")],
                default="Medium",
            ),
        ),
    ]
